name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: Setup
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.62.2'

      - name: Build
        run: make build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          EXTERNAL_REPOSITORY: nikodegtyaryov/nikodegtyaryov.github.io
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./blog/public
